export const WORLD_COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia (Czech Republic)',
  'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
  'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
  'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
  'Haiti', 'Holy See', 'Honduras', 'Hungary',
  'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Italy', 'Ivory Coast',
  'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (formerly Burma)',
  'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
  'Oman',
  'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar',
  'Romania', 'Russia', 'Rwanda',
  'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe'
];

export const POPULAR_CITIES = [
  { name: 'Riyadh', country: 'Saudi Arabia', code: 'RUH' },
  { name: 'Jeddah', country: 'Saudi Arabia', code: 'JED' },
  { name: 'Dammam', country: 'Saudi Arabia', code: 'DMM' },
  { name: 'Medina', country: 'Saudi Arabia', code: 'MED' },
  { name: 'Dubai', country: 'United Arab Emirates', code: 'DXB' },
  { name: 'Abu Dhabi', country: 'United Arab Emirates', code: 'AUH' },
  { name: 'Doha', country: 'Qatar', code: 'DOH' },
  { name: 'Muscat', country: 'Oman', code: 'MCT' },
  { name: 'Manama', country: 'Bahrain', code: 'BAH' },
  { name: 'Kuwait City', country: 'Kuwait', code: 'KWI' },
  { name: 'Cairo', country: 'Egypt', code: 'CAI' },
  { name: 'Istanbul', country: 'Turkey', code: 'IST' },
  { name: 'London', country: 'United Kingdom', code: 'LHR' },
  { name: 'Paris', country: 'France', code: 'CDG' },
  { name: 'New York', country: 'USA', code: 'JFK' },
  { name: 'Tokyo', country: 'Japan', code: 'HND' },
  { name: 'Singapore', country: 'Singapore', code: 'SIN' },
  { name: 'Bangkok', country: 'Thailand', code: 'BKK' },
  { name: 'Frankfurt', country: 'Germany', code: 'FRA' },
  { name: 'Amsterdam', country: 'Netherlands', code: 'AMS' },
  { name: 'Madrid', country: 'Spain', code: 'MAD' },
  { name: 'Rome', country: 'Italy', code: 'FCO' },
  { name: 'Hong Kong', country: 'Hong Kong', code: 'HKG' },
  { name: 'Seoul', country: 'South Korea', code: 'ICN' },
  { name: 'Mumbai', country: 'India', code: 'BOM' },
  { name: 'Delhi', country: 'India', code: 'DEL' },
  { name: 'Sydney', country: 'Australia', code: 'SYD' },
  { name: 'Los Angeles', country: 'USA', code: 'LAX' },
  { name: 'San Francisco', country: 'USA', code: 'SFO' },
  { name: 'Chicago', country: 'USA', code: 'ORD' },
  { name: 'Toronto', country: 'Canada', code: 'YYZ' },
  { name: 'Zurich', country: 'Switzerland', code: 'ZRH' },
  { name: 'Geneva', country: 'Switzerland', code: 'GVA' },
  { name: 'Vienna', country: 'Austria', code: 'VIE' },
  { name: 'Dhaka', country: 'Bangladesh', code: 'DAC' },
  { name: 'Chittagong', country: 'Bangladesh', code: 'CGP' },
  { name: 'Sylhet', country: 'Bangladesh', code: 'ZYL' },
  { name: 'Colombo', country: 'Sri Lanka', code: 'CMB' },
  { name: 'Malé', country: 'Maldives', code: 'MLE' },
  { name: 'Kuala Lumpur', country: 'Malaysia', code: 'KUL' },
  { name: 'Jakarta', country: 'Indonesia', code: 'CGK' },
  { name: 'Manila', country: 'Philippines', code: 'MNL' },
  { name: 'Johannesburg', country: 'South Africa', code: 'JNB' },
  { name: 'Casablanca', country: 'Morocco', code: 'CMN' },
  { name: 'Nairobi', country: 'Kenya', code: 'NBO' },
  { name: 'São Paulo', country: 'Brazil', code: 'GRU' },
  { name: 'Mexico City', country: 'Mexico', code: 'MEX' }
];

export const GLOBAL_AIRPORTS = [
  ...POPULAR_CITIES,
  { name: 'Berlin', country: 'Germany', code: 'BER' },
  { name: 'Munich', country: 'Germany', code: 'MUC' },
  { name: 'Barcelona', country: 'Spain', code: 'BCN' },
  { name: 'Lisbon', country: 'Portugal', code: 'LIS' },
  { name: 'Stockholm', country: 'Sweden', code: 'ARN' },
  { name: 'Oslo', country: 'Norway', code: 'OSL' },
  { name: 'Copenhagen', country: 'Denmark', code: 'CPH' },
  { name: 'Helsinki', country: 'Finland', code: 'HEL' },
  { name: 'Warsaw', country: 'Poland', code: 'WAW' },
  { name: 'Prague', country: 'Czech Republic', code: 'PRG' },
  { name: 'Budapest', country: 'Hungary', code: 'BUD' },
  { name: 'Athens', country: 'Greece', code: 'ATH' },
  { name: 'Tel Aviv', country: 'Israel', code: 'TLV' },
  { name: 'Beirut', country: 'Lebanon', code: 'BEY' },
  { name: 'Amman', country: 'Jordan', code: 'AMM' },
  { name: 'Tehran', country: 'Iran', code: 'IKA' },
  { name: 'Baghdad', country: 'Iraq', code: 'BGW' },
  { name: 'Islamabad', country: 'Pakistan', code: 'ISB' },
  { name: 'Karachi', country: 'Pakistan', code: 'KHI' },
  { name: 'Lahore', country: 'Pakistan', code: 'LHE' },
  { name: 'Kathmandu', country: 'Nepal', code: 'KTM' },
  { name: 'Tashkent', country: 'Uzbekistan', code: 'TAS' },
  { name: 'Almaty', country: 'Kazakhstan', code: 'ALA' },
  { name: 'Beijing', country: 'China', code: 'PEK' },
  { name: 'Shanghai', country: 'China', code: 'PVG' },
  { name: 'Guangzhou', country: 'China', code: 'CAN' },
  { name: 'Taipei', country: 'Taiwan', code: 'TPE' },
  { name: 'Osaka', country: 'Japan', code: 'KIX' },
  { name: 'Melbourne', country: 'Australia', code: 'MEL' },
  { name: 'Brisbane', country: 'Australia', code: 'BNE' },
  { name: 'Perth', country: 'Australia', code: 'PER' },
  { name: 'Auckland', country: 'New Zealand', code: 'AKL' },
  { name: 'Vancouver', country: 'Canada', code: 'YVR' },
  { name: 'Montreal', country: 'Canada', code: 'YUL' },
  { name: 'Boston', country: 'USA', code: 'BOS' },
  { name: 'Miami', country: 'USA', code: 'MIA' },
  { name: 'Houston', country: 'USA', code: 'IAH' },
  { name: 'Dallas', country: 'USA', code: 'DFW' },
  { name: 'Washington D.C.', country: 'USA', code: 'IAD' },
  { name: 'Seattle', country: 'USA', code: 'SEA' },
  { name: 'Atlanta', country: 'USA', code: 'ATL' },
  { name: 'Denver', country: 'USA', code: 'DEN' },
  { name: 'Bogotá', country: 'Colombia', code: 'BOG' },
  { name: 'Lima', country: 'Peru', code: 'LIM' },
  { name: 'Santiago', country: 'Chile', code: 'SCL' },
  { name: 'Buenos Aires', country: 'Argentina', code: 'EZE' },
  { name: 'Rio de Janeiro', country: 'Brazil', code: 'GIG' },
  { name: 'Lagos', country: 'Nigeria', code: 'LOS' },
  { name: 'Addis Ababa', country: 'Ethiopia', code: 'ADD' },
  { name: 'Cairo', country: 'Egypt', code: 'CAI' },
  { name: 'Cape Town', country: 'South Africa', code: 'CPT' },
  { name: 'Mauritius', country: 'Mauritius', code: 'MRU' },
  { name: 'Seychelles', country: 'Seychelles', code: 'SEZ' }
];
